services:
    wjb\AutocompleteBundle\Controller\AutocompleteController:
        arguments: ['@wjb_autocomplete.object_transformer']
        tags: ['controller.service_arguments']

    wjb_autocomplete.autocomplete_entity_type:
        class: wjb\AutocompleteBundle\Form\Type\AutocompleteType
        arguments: ['@wjb_autocomplete.object_transformer', '@?doctrine.orm.entity_manager']
        tags:
            - { name: 'form.type' }

    wjb_autocomplete.autocomplete_config_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator']
        arguments: ['injected']

    wjb_autocomplete.object_transformer:
        class: wjb\AutocompleteBundle\Service\ObjectTransformer
        arguments: ['@property_accessor']



